name: Enforce Pull Request Title includes Linear Issue Key

description: Check that a PR title starts with a Linear Issue Key

inputs:
  projectKey:
    description: 'A specific Jira Project Key that must be included.'
    required: false

runs:
  using: node14
  main: dist/index.js
